### ISSUE TITLE
Bug with keel on windows

### ISSUE THREAD

**Issue by TDMSundriyal** [teamkeel/keel#1522]
Cant set up the keel backend properly. 
Steps followed by me are :
1. npm install --global keel
2. keel --version
3. mkdir my-app && cd my-app
4. keel init

Following is the stacktrace:
goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.14/x64/src/runtime/debug/stack.go:24 +0x65
github.com/teamkeel/keel/cmd.panicHandler()
        /home/runner/work/keel/keel/cmd/init.go:81 +0x5a5
panic({0x137d840, 0xc00070af50})
        /opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
github.com/teamkeel/keel/cmd.initStepCreateProject(0xc000054300)
        /home/runner/work/keel/keel/cmd/init.go:353 +0x44c
github.com/teamkeel/keel/cmd.glob..func3(0x1fa2360?, {0x200e190?, 0x0?, 0x0?})
        /home/runner/work/keel/keel/cmd/init.go:52 +0x30d
github.com/spf13/cobra.(*Command).execute(0x1fa2360, {0x200e190, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x1fa25e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/teamkeel/keel/cmd.Execute()
        /home/runner/work/keel/keel/cmd/root.go:47 +0x25
main.main()
        /home/runner/work/keel/keel/cmd/keel/main.go:6 +0x17

**Comment by tomfrew** [comment]
Hey @TDMSundriyal 
So sorry this got missed. Thanks for reporting this. We don't officially support windows yet but we will take a look and try and get this working. Just to confirm this happens as soon as you run `keel init` or does some of the init CLI UI display?
