### ISSUE TITLE
Keel Init problem

### ISSUE THREAD

**Issue by RoyaghRamo** [teamkeel/keel#1535]
Hello, i'm new to keel. I've had some difficulties installing keel globally at first. And now I tried creating a new project using "keel init". And I got this error

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.20.14/x64/src/runtime/debug/stack.go:24 +0x65
github.com/teamkeel/keel/cmd.panicHandler()
        /home/runner/work/keel/keel/cmd/init.go:81 +0x5a5
panic({0xe5fae0, 0xc000292170})
        /opt/hostedtoolcache/go/1.20.14/x64/src/runtime/panic.go:884 +0x213
github.com/teamkeel/keel/cmd.initStepCreateProject(0xc0006d69c0)
        /home/runner/work/keel/keel/cmd/init.go:353 +0x46c
github.com/teamkeel/keel/cmd.glob..func3(0x1a863c0?, {0x1af21f0?, 0x0?, 0x0?})
        /home/runner/work/keel/keel/cmd/init.go:52 +0x30d
github.com/spf13/cobra.(*Command).execute(0x1a863c0, {0x1af21f0, 0x0, 0x0})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0x1a86640)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/teamkeel/keel/cmd.Execute()
        /home/runner/work/keel/keel/cmd/root.go:47 +0x25
main.main()
        /home/runner/work/keel/keel/cmd/keel/main.go:6 +0x17

Can someone tell me what to do? 
Thanks

**Comment by tomfrew** [comment]
Hey @RoyaghRamo 
So sorry this got missed. What operating system are you using?
